[project]
name = "ml4msd-mlip"
version = "0.1.0"
description = "Environment for MatCalc and MACE"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "jupyter>=1.1.1",
    "mace-torch>=0.3.12",
    "matcalc>=0.4.3",
    "mp-api>=0.45.12",
    "nglview>=4.0",
]
